sudo: required
dist: trusty

language: c++

script:
 - mkdir build
 - cd build
 - export CXXFLAGS=${CI_CXX_FLAGS} LDFLAGS=${CI_LDFLAGS}
 - cmake .. -G Ninja -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_BUILD_TYPE=Release
 - ninja
 - ctest --output-on-failure

matrix:
  include:
    - os: linux
      compiler: gcc-7
      env:
        - C_COMPILER=gcc-7
        - CXX_COMPILER=g++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libgl1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - libxcb-util0-dev
            - libxcb-image0-dev
      before_install:
        - . ./ci/setup_cmake.sh 3.13.2 Linux
        - . ./ci/setup_ninja.sh 1.8.2 linux
    - os: linux
      compiler: gcc-8
      env:
        - C_COMPILER=gcc-8
        - CXX_COMPILER=g++-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libgl1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - libxcb-util0-dev
            - libxcb-image0-dev
      before_install:
        - . ./ci/setup_cmake.sh 3.13.2 Linux
        - . ./ci/setup_ninja.sh 1.8.2 linux
    - os: linux
      compiler: clang-5.0
      env:
        - C_COMPILER=clang-5.0
        - CXX_COMPILER=clang++-5.0
      addons:
        apt:
          packages:
            - clang-5.0
            - libgl1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - libxcb-util0-dev
            - libxcb-image0-dev
          sources:
            - llvm-toolchain-trusty-5.0
      before_install:
        - . ./ci/setup_cmake.sh 3.13.2 Linux
        - . ./ci/setup_ninja.sh 1.8.2 linux
        - . ./ci/setup_libcxx.sh 5.0.2 /usr
    - os: linux
      compiler: clang-6.0
      env:
        - C_COMPILER=clang-6.0
        - CXX_COMPILER=clang++-6.0
      addons:
        apt:
          packages:
            - clang-6.0
            - libgl1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - libxcb-util0-dev
            - libxcb-image0-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
      before_install:
        - . ./ci/setup_cmake.sh 3.13.2 Linux
        - . ./ci/setup_ninja.sh 1.8.2 linux
        - . ./ci/setup_libcxx.sh 6.0.1 /usr
    - os: linux
      compiler: clang-7.0
      env:
        - C_COMPILER=clang-7
        - CXX_COMPILER=clang++-7
      addons:
        apt:
          packages:
            - clang-7
            - libgl1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - libxcb-util0-dev
            - libxcb-image0-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
      before_install:
        - . ./ci/setup_cmake.sh 3.13.2 Linux
        - . ./ci/setup_ninja.sh 1.8.2 linux
        - . ./ci/setup_libcxx.sh 7.0.1 /usr
    - os: linux
      compiler: clang-8.0
      env:
        - C_COMPILER=clang-8
        - CXX_COMPILER=clang++-8
      addons:
        apt:
          packages:
            - clang-8
            - libgl1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - libxcb-util0-dev
            - libxcb-image0-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-8
      before_install:
        - . ./ci/setup_cmake.sh 3.13.2 Linux
        - . ./ci/setup_ninja.sh 1.8.2 linux
        - . ./ci/setup_libcxx.sh 8.0.0 /usr
    - os: osx
      osx_image: xcode9.4
      env:
        - C_COMPILER=clang
        - CXX_COMPILER=clang++
        - CI_CXX_FLAGS='-Wno-unused-command-line-argument -nostdinc++ -isystem /Users/travis/libc++/include/c++/v1'
        - CI_LDFLAGS='-L /Users/travis/libc++/lib'
      before_install:
        - . ./ci/setup_cmake.sh 3.13.2 Darwin
        - . ./ci/setup_ninja.sh 1.8.2 mac
        - . ./ci/setup_libcxx.sh 8.0.0 /Users/travis/libc++
    - os: osx
      osx_image: xcode10
      env:
        - C_COMPILER=clang
        - CXX_COMPILER=clang++
        - CI_CXX_FLAGS='-Wno-unused-command-line-argument -nostdinc++ -isystem /Users/travis/libc++/include/c++/v1'
        - CI_LDFLAGS='-L /Users/travis/libc++/lib'
      before_install:
        - . ./ci/setup_cmake.sh 3.13.2 Darwin
        - . ./ci/setup_ninja.sh 1.8.2 mac
        - . ./ci/setup_libcxx.sh 8.0.0 /Users/travis/libc++
    - os: osx
      osx_image: xcode10.1
      env:
        - C_COMPILER=clang
        - CXX_COMPILER=clang++
        - CI_CXX_FLAGS='-Wno-unused-command-line-argument -nostdinc++ -isystem /Users/travis/libc++/include/c++/v1'
        - CI_LDFLAGS='-L /Users/travis/libc++/lib'
      before_install:
        - . ./ci/setup_cmake.sh 3.13.2 Darwin
        - . ./ci/setup_ninja.sh 1.8.2 mac
        - . ./ci/setup_libcxx.sh 8.0.0 /Users/travis/libc++
